[package]
name = "show"
version = "0.1.0"
authors = ["Sebastian Köln <sebk@rynx.org>"]

[dependencies]
image = { version = "0.12.0", default-features = false }
piston_window = "*"
palette = "*"
num-complex = "*"
pistoncore-input = "*"
simd = "*"
